FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /App

COPY ../ ./

WORKDIR /App
RUN dotnet restore ./Kull.Data.Test/Kull.Data.Test.csproj


FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /App
COPY --from=build-env /App/ .

ENTRYPOINT ["dotnet", "test", "./Kull.Data.Test/Kull.Data.Test.csproj"]